//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LutronQuantum.Data_Modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObixDevice
    {
        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceType { get; set; }
        public string DeviceUrl { get; set; }
        public string Unit { get; set; }
        public string Value { get; set; }
        public string Status { get; set; }
        public string ValueType { get; set; }
        public int object_instance { get; set; }

        public bool isActive { get; set; }
        public System.DateTime DateOfEntry { get; set; }
    }
}
